import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainPageHeader from "./MainPage/MainPageHeader"; // Імпорт хедера
import MainPageFooter from "./MainPage/MainPageFooter"; // Імпорт футера

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MainPageHeader /> {/* Хедер на всіх сторінках */}
        <main>{children}</main> {/* Вміст сторінок */}
        <MainPageFooter /> {/* Футер на всіх сторінках */}
      </body>
    </html>
  );
}